firstNumber = int(input("Enter First Number : "))
secondNumer = int(input("Enter Second Number : "))

print("Addition x + y : " + str(firstNumber + secondNumer))
print("Subtraction x - y : " + str(firstNumber - secondNumer))
print("Multiplication x * y : " + str(firstNumber * secondNumer))
print("Division (float) x / y : " + str(firstNumber / secondNumer))
print("Division (floor) x // y : " + str(firstNumber // secondNumer))
print("Modulus x % y : " + str(firstNumber % secondNumer))
print("Power x ** y : " + str(firstNumber ** secondNumer))
print("Power y ** x : " + str(secondNumer ** firstNumber))
